const SET_USER_SIGN_IN = "SET_USER_SIGN_IN";
const SET_USER_SIGN_OUT = "SET_USER_SIGN_OUT";
const SET_NEW_STREAM = "SET_NEW_STREAM";
const GET_ALL_STREAMS = "GET_ALL_STREAMS";
const GET_STREAM = "GET_STREAM";
const SET_UPDATE_STREAM = "SET_UPDATE_STREAM";
const SET_DELETE_STREAM = "SET_DELETE_STREAM";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  SET_USER_SIGN_IN,
  SET_USER_SIGN_OUT,
  SET_NEW_STREAM,
  GET_ALL_STREAMS,
  GET_STREAM,
  SET_UPDATE_STREAM,
  SET_DELETE_STREAM,
};
